### ISSUE TITLE
Comentar el código en interruptorPulsado(:)

### ISSUE THREAD

**Issue by pedrocursos** [pedrocursos/CambiaFon#1]
Comentar las líneas de código que hay en la función interruptorPulsado(:)

https://github.com/pedrocursos/CambiaFon/blob/9afeed8d93f71718afd765025a5386cb564b3057/CambiaFon/CambiaFon/ViewController.swift#L33-L40

**Comment by josemagithub** [comment]
Las comentaré y subiré un PR.

**Comment by pedrocursos** [comment]
Ok

**Comment by pedrocursos** [comment]
Gracias @josemagithub
