### ISSUE TITLE
Añadir animación a la acción On/Off del interruptor

### ISSUE THREAD

**Issue by teregithub** [pedrocursos/CambiaFon#3]
Añadir una animación con efecto muelle para que sea más agradable para el usuario el aumento de tamaño del interruptor al ser pulsado. Hacer esta animación en la función interruptorPulsado(:)

https://github.com/pedrocursos/CambiaFon/blob/79c2b5547018bb1e5b7ab2620fd66aabccddb542/CambiaFon/CambiaFon/ViewController.swift#L42-L43

**Comment by teregithub** [comment]
Me encantaría hacer esta animación, ok?

**Comment by pedrocursos** [comment]
Buena idea @teregithub. Sube tu propuesta en un PR y una vez que la vea te doy mi opinión.

**Comment by pedrocursos** [comment]
La animación del escalado es sutil y elegante. Gracias @teregithub por tu contribución al proyecto.
